[features]
seeds = false
[programs.localnet]
mysolanaapp = "DwEiDZdjyMBRsjiQPkU4YogfSZqS5qNCkuspgSU7fcpL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/davib/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
